apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.name" . }}
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: {{ .Values.ollama.servicePort }}
    targetPort: {{ .Values.ollama.servicePort }}
