apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.name" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ollama.selectorLabels" . | nindent 4 }}
{{- with .Values.ollama.service }}
  type: {{ .type }}
  ports:
  - protocol: TCP
    name: http
    port: http
    targetPort: {{ .port }}
{{- end }}
