apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    app: open-webui
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.webui.volumeSize }}
