apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
{{- with .Values.webui.service }}
  type: {{ .type }}
  ports:
  - protocol: TCP
    port: {{ .port }}
    targetPort: {{ .containerPort }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
{{- end }}
