apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.webui.persistence.size }}
