apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-webui.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.webui.image }}
        ports:
        - containerPort: 8080
        {{- if .Values.webui.resources }}
        resources: {{- toYaml .Values.webui.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
        env:
        - name: OLLAMA_API_BASE_URL
          value: {{ printf "http://%s.%s.svc.cluster.local:%s/api" (include "ollama.name" .) (.Release.Namespace) (.Values.ollama.servicePort) | quote }}
        tty: true
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: {{ include "open-webui.name" . }}
