apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-webui.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.webui.image }}
        ports:
        - name: http
          containerPort: {{ .Values.webui.service.containerPort }}
        {{- with .Values.webui.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
        env:
        - name: OLLAMA_API_BASE_URL
          value: {{ printf "http://%s.%s.svc.cluster.local:%s/api" (include "ollama.name" .) (.Release.Namespace) (.Values.ollama.servicePort) | quote }}
        tty: true
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: {{ include "open-webui.name" . }}
