services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]
    networks:
      - app

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - redis
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=password
      - ENABLE_RATE_LIMIT=true
      - ENABLE_RAG_PARENT_RETRIEVER=true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - app

volumes:
  open-webui: {}

networks:
  app:
    external: true
    name: "app"