ollama:
  replicaCount: 1
  image: ollama/ollama:latest
  resources:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"
      nvidia.com/gpu: "0"
  volumeSize: 30Gi
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    port: 80
    containerPort: 11434
  gpu:
    enabled: false

webui:
  replicaCount: 1
  image: ghcr.io/open-webui/open-webui:main
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  ingress:
    enabled: true
    annotations: {}
    # Use appropriate annotations for your Ingress controller, e.g., for NGINX:
      # nginx.ingress.kubernetes.io/rewrite-target: /
    host: open-webui.minikube.local
  persistence:
    enabled: true
    size: 2Gi
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    port: 80
    containerPort: 8080
    nodePort: ""
