ollama:
  replicaCount: 1
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: Always
  resources: {}
  persistence:
    enabled: true
    size: 30Gi
  nodeSelector: {}
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  service:
    type: ClusterIP
    port: 80
    containerPort: 11434
  gpu:
    enabled: false

webui:
  replicaCount: 1
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: Always
  resources: {}
  ingress:
    enabled: disable
    # -- Use appropriate annotations for your Ingress controller, e.g., for NGINX:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    annotations: {}
    host: ""
  persistence:
    enabled: true
    size: 2Gi
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    port: 80
    containerPort: 8080
    nodePort: ""
